### ISSUE TITLE
Funktionsübersicht - Konkrete Umsetzungen

### ISSUE THREAD

**Issue by alexsuter** [accefa/doku#36]
- [ ] #41 Konkrete Umsetzung - Ortung Korb - Pixy
- [ ] #42 Konkrete Umsetzung - Ortung Korb - Laser
- [ ] #43 Konkrete Umsetzung - Ortung Korb - Ultraschall
- [ ] #44 Konkrete Umsetzung - Ortung Korb - Optik (Java, Python)
- [ ] #45 Konkrete Umsetzung - Kommunikation
